bingo_coffquiz_project/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from django.conf import settings
from django.conf.urls.static import static
from coffquiz import views
from registration.backends.simple.views import RegistrationView 


class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('coffquiz:register_profile')

urlpatterns = [
    path('', views.index, name='index'),
    path('coffquiz/', include('coffquiz.urls')),
    path('admin/', admin.site.urls),
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coffquiz/urls.py
from django.urls import path
from coffquiz import views

app_name = 'coffquiz'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('coffee/<slug:coffee_name_slug>/', views.show_coffee, name='show_coffee'),
    path('coffee/articles/<slug:article_title_slug>/', views.show_article, name='show_article'),
    path('add_coffee/', views.add_coffee, name='add_coffee'),
    path('coffee/<slug:coffee_name_slug>/add_article/', views.add_article, name='add_article'),
    path('coffee/articles/<slug:article_title_slug>/add_comment/', views.add_comment, name='add_comment'),
    path('add_comment/', views.add_comment, name='add_comment'),
    path('goto/', views.goto_article, name='goto'),
    path('register_profile/', views.register_profile, name='register_profile'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path('like_coffee/',views.LikeCategoryView.as_view(),name='like_coffee'),
    path('suggest/',views.CoffeeSuggestionView.as_view(),name='suggest'),
    path('coffee/', views.all_coffee, name='all_coffee'),
    path('articles/', views.all_articles, name='all_articles'),
]

coffquiz/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.utils import timezone

class Coffee(models.Model):
    name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(unique=True)
    likes = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    time = models.DateTimeField(default=timezone.now)
    picture = models.ImageField(upload_to='coffee_images', blank=True)
    description = models.TextField(blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        if self.views<0:
            self.views=0
        super(Coffee, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Coffee'

    def __str__(self):
        return self.name

class Article(models.Model):
    title = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(unique=True)
    coffee = models.ForeignKey(Coffee, on_delete=models.CASCADE)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    time = models.DateTimeField(default=timezone.now)
    picture = models.ImageField(upload_to='article_images', blank=True)
    content = models.TextField(blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Article, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatar_images', blank=True)
    signature = models.CharField(max_length=128, blank=True)

    def __str__(self):
        return self.user.username

class LikeCoffee(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    coffee = models.ForeignKey(Coffee, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Like Coffee'

    def __str__(self):
        return self.user.username + 'likes' + self.coffee.name

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    comments = models.CharField(max_length=128)
    time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.comments

coffquiz/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils import timezone
from coffquiz.models import Coffee, Article, UserProfile, Comment

class CoffeeForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the coffee name.")
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    time = forms.DateTimeField(widget=forms.HiddenInput(), initial=timezone.now)
    picture = forms.ImageField(help_text="Please upload a coffee picture.", required=False)
    description = forms.CharField(widget=forms.Textarea, help_text="Please enter the coffee introduction.")

    class Meta:
        model = Coffee
        exclude = ('user',)

class ArticleForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the review title.")
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    time = forms.DateTimeField(widget=forms.HiddenInput(), initial=timezone.now)
    picture = forms.ImageField(help_text="Please upload a coffee picture.", required=False)
    content = forms.CharField(widget=forms.Textarea, help_text="Please enter the content.") 

    class Meta:
        model = Article
        exclude = ('writer', 'coffee')

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('avatar', 'signature')

class CommentForm(forms.ModelForm):
    comments = forms.CharField(max_length=128, widget=forms.Textarea, help_text="Please enter the comment content.")
    time = forms.DateTimeField(widget=forms.HiddenInput(), initial=timezone.now)
    class Meta:
        model = Comment
        exclude = ('article', 'user',)

coffquiz/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from datetime import datetime
from coffquiz.models import Coffee, Article, UserProfile, Comment
from coffquiz.forms import CoffeeForm, ArticleForm, UserForm, UserProfileForm, CommentForm
from django.contrib.auth.models import User
from coffquiz.bing_search import run_query

def index(request):
    coffee_list = Coffee.objects.order_by('-likes')[:5]
    article_list = Article.objects.order_by('-views')[:5]

    context_dict = {}
    context_dict['introduction'] = 'Coffquiz is a coffee exchange website, \
    please feel free to add various coffee products and post reviews on them.'
    context_dict['coffeelist'] = coffee_list
    context_dict['articles'] = article_list

    return render(request, 'coffquiz/index.html', context=context_dict)

def about(request):
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    return render(request, 'coffquiz/about.html', context=context_dict)

def show_coffee(request, coffee_name_slug):
    context_dict = {}
    try:
        coffee = Coffee.objects.get(slug=coffee_name_slug)
        articles = Article.objects.filter(coffee=coffee).order_by('-views')

        context_dict['coffee'] = coffee
        context_dict['articles'] = articles
    
    except Coffee.DoesNotExist:
        context_dict['coffee'] = None
        context_dict['articles'] = None

    # Start search functionality code. 
    if request.method == 'POST':
        if request.method == 'POST':
            query = request.POST['query'].strip()
            
            if query:
                context_dict['result_list'] = run_query(query)
                context_dict['query'] = query

    return render(request, 'coffquiz/coffee.html', context=context_dict)

def show_article(request, article_title_slug):
    context_dict = {}
    try:
        article = Article.objects.get(slug=article_title_slug)
        comments = Comment.objects.filter(article=article)

        context_dict['article'] = article
        context_dict['comments'] = comments
    
    except Coffee.DoesNotExist:
        context_dict['article'] = None
        context_dict['comments'] = None
    
    return render(request, 'coffquiz/article.html', context=context_dict)

def all_coffee(request):
    allCoffee = Coffee.objects.all().order_by('-likes')
    context_dict = {}
    context_dict['all_coffee'] = allCoffee

    return render(request, 'coffquiz/all_coffee.html', context=context_dict)

def all_articles(request):
    allArticles = Article.objects.all().order_by('-views')
    context_dict = {}
    context_dict['all_articles'] = allArticles

    return render(request, 'coffquiz/all_Articles.html', context=context_dict)

@login_required
def add_coffee(request):
    user = User.objects.get(username=request.user)
    form = CoffeeForm()

    if request.method == 'POST':
        form = CoffeeForm(request.POST)
        if form.is_valid():
            coffee = form.save(commit=False)
            coffee.user = user
            coffee.save()
            
            return redirect('coffquiz:index')
        else:
            print(form.errors)
    return render(request, 'coffquiz/add_coffee.html', {'form': form})

@login_required
def add_comment(request, article_title_slug):
    try:
        article = Article.objects.get(slug=article_title_slug)
    except:
        article = None
    
    if article is None:
        return redirect(reverse('coffquiz:index'))

    user = User.objects.get(username=request.user)
    
    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            if article:
                comment = form.save(commit=False)
                comment.article = article
                comment.user = user
                comment.save()
                return redirect(reverse('coffquiz:show_article', kwargs={'article_title_slug':article_title_slug}))
            else:
                print(form.errors)

    context_dict = {'form': form, 'article': article}
    return render(request, 'coffquiz/add_comment.html', context=context_dict)            


@login_required
def add_article(request, coffee_name_slug):
    user = User.objects.get(username=request.user)
    try:
        coffee = Coffee.objects.get(slug=coffee_name_slug)
    except Coffee.DoesNotExist:
        coffee = None
    
    if coffee is None:
        return redirect(reverse('coffquiz:index'))

    form = ArticleForm()

    if request.method == 'POST':
        form = ArticleForm(request.POST)

        if form.is_valid():
            if coffee:
                article = form.save(commit = False)
                article.coffee = coffee
                article.writer = user
                article.save()

                return redirect(reverse('coffquiz:show_coffee', kwargs={'coffee_name_slug':coffee_name_slug}))

        else:
            print(form.errors)
    context_dict = {'form': form, 'coffee': coffee}
    return render(request, 'coffquiz/add_article.html', context=context_dict)

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))

    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')
    
    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie
        
    request.session['visits'] = visits

# This is used to record the number of views of the article
def goto_article(request):
    if request.method == 'GET':
        article_id = request.GET.get('article_id')

        try:
            selected_article = Article.objects.get(slug=article_id)
        except Article.DoesNotExist:
            return redirect(reverse('coffquiz:index'))

        selected_article.views = selected_article.views + 1
        selected_article.save()

        return redirect(reverse('coffquiz:show_article', kwargs={'article_title_slug':selected_article.slug}))

    return redirect(reverse('coffquiz:index'))

@login_required 
def register_profile(request):
    form = UserProfileForm()

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)

        if form.is_valid():
            user_profile = form.save(commit=False) 
            user_profile.user = request.user 
            user_profile.save()

            return redirect(reverse('coffquiz:index')) 
        else:
            print(form.errors)

    context_dict = {'form': form}
    return render(request, 'coffquiz/profile_registration.html', context_dict)

class ProfileView(View):
    def get_user_details(self, username):
        try:
            user = User.objects.get(username=username) 
        except User.DoesNotExist:
            return None

        user_profile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({'signature': user_profile.signature, 'avatar': user_profile.avatar}) 
        return (user, user_profile, form) 
        
    @method_decorator(login_required) 
    def get(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username) 
        except TypeError:
            return redirect(reverse('coffquiz:index')) 
        
        context_dict = {'user_profile': user_profile, 'selected_user': user, 'form': form} 
        return render(request, 'coffquiz/profile.html', context_dict) 
        
    @method_decorator(login_required) 
    def post(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username) 
        except TypeError:
            return redirect(reverse('coffquiz:index')) 
        
        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            form.save(commit=True) 
            return redirect('coffquiz:profile', user.username) 
        else:
            print(form.errors)
        
        context_dict = {'user_profile': user_profile, 'selected_user': user, 'form': form}
        return render(request, 'coffquiz/profile.html', context_dict)

# this class is for add likes
class LikeCategoryView(View):
    @method_decorator(login_required())
    def get(self, request):
        coffee_id = request.GET['coffee_id']

        try:
            coffee = Coffee.objects.get(id=int(coffee_id))
        except Coffee.DoesNotExist:
            return HttpResponse(-1)
        except ValueError:
            return HttpResponse(-1)

        coffee.likes = coffee.likes + 1
        coffee.save()

        return HttpResponse(coffee.likes)


'''
    The following part is for coffee search function in siderbar
'''

def get_coffee_list(max_results=0, starts_with=''):
    # this function is for get the coffee list
    coffee_list = []

    if starts_with:
        coffee_list = Coffee.objects.filter(name__contains=starts_with)

    print(coffee_list)

    # if max_results is 0, all result will be returned
    if max_results > 0:
        if len(coffee_list) > max_results:
            coffee_list = coffee_list[:max_results]

    return coffee_list


class CoffeeSuggestionView(View):
    def get(self, request):
        if 'suggestion' in request.GET:
            suggestion = request.GET['suggestion']
        else:
            suggestion = ''

        coffee_list = get_coffee_list(max_results=8,

templates/coffquiz/add_article.html
{% extends 'coffquiz/base.html' %}
{% load static %}

{% block title_block %}
    Add a Article
{% endblock %}

{% block body_block %}
    <div class="jumbotron p-4"> 
        <div class="container"> 
            <h1 class="jumbotron-heading">Add an Article to {{ coffee.name }}</h1>
        </div> 
    </div> 
    <div class="container"> 
        <div class="row"> 
            <form role="form" id="article_form" method="post" action="{% url 'coffquiz:add_article' coffee.slug %}"> 
                {% csrf_token %} 
                {% for hidden in form.hidden_fields %} 
                    {{ hidden }} 
                {% endfor %} 
                {% for field in form.visible_fields %} 
                    {{ field.errors }} 
                    {{ field.help_text }}<br /> 
                    {{ field }}<br /> 
                <div class="p-2"></div> 
                {% endfor %} 
            <br /> 
            <button class="btn btn-primary" type="submit" name="submit">Add Article</button> 
            <div class="p-5"></div> 
            </form> 
        </div> 
    </div>
{% endblock %}

templates/coffquiz/add_coffee.html
{% extends 'coffquiz/base.html' %}
{% load static %}

{% block title_block %}
    Add a Coffee
{% endblock %}

{% block body_block %}
    <div class="jumbotron p-4"> 
        <div class="container"> 
        <h1 class="jumbotron-heading">Add a Coffee</h1>
        </div> 
       </div> 
    <div class="container"> 
        <div class="row"> 
            <form role="form" id="coffee_form" method="post" action="{% url 'coffquiz:add_coffee' %}">
                {% csrf_token %} 
                {% for hidden in form.hidden_fields %} 
                    {{ hidden }} 
                {% endfor %} 
                {% for field in form.visible_fields %} 
                    {{ field.errors }} 
                    {{ field.help_text }}<br /> 
                    {{ field }}<br /> 
                    <div class="p-2"></div> 
                {% endfor %} 
                <br /> 
                <button class="btn btn-primary" type="submit" name="submit">Create Coffee</button> 
                <div class="p-5"></div> 
        </form> 
    </div>
</div> 
{% endblock %}

templates/coffquiz/add_comment.html
{% extends 'coffquiz/base.html' %}
{% load static %}

{% block title_block %}
    {% if article %}
        {{ article.title }}
    {% else %}
        Unknown Article
    {% endif %}
{% endblock %}

{% block body_block %}
    <div class="jumbotron p-4"> 
        <div class="container"> 
            <h1 class="jumbotron-heading">Add a Comment to {{ article.title }}</h1>
        </div> 
    </div>
    <form id="add_comment_form" method="post" action="{% url 'coffquiz:add_comment' article.slug %}">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}<br />
            {{ field }}<br />
        {% endfor %}
        <br />
        <button class="btn btn-primary" type="submit" name="submit">Add Comment</button> 
    </form>
{% endblock %}

templates/coffquiz/all_coffee.html
{% extends 'coffquiz/base.html' %}
{% load static %}

{% block title_block %}
    All Coffee
{% endblock %}

{% block body_block %}
    <div class="jumbotron p-4"> 
        <div class="container"> 
            <h1 class="jumbotron-heading">All Coffee</h1>
        </div> 
    </div>
    {% if all_coffee %}
        <ul>
        {% for coffee in all_coffee %}
            <li>
                <a href="{% url 'coffquiz:show_coffee' coffee.slug %}">{{ coffee.name }}</a>
                {% if coffee.likes > 1 %}
                    ({{ coffee.likes }} likes)
                {% elif coffee.likes == 1 %}
                    ({{ coffee.likes }} likes)
                {% endif %}
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <strong>No coffee currently in this website.</strong><br />
    {% endif %}
    {% if user.is_authenticated %}
        <a href="{% url 'coffquiz:add_coffee' %}">Add Coffee</a><br />
    {% endif %}
{% endblock %}

templates/coffquiz/article.html
{% extends 'coffquiz/base.html' %}
{% load static %}

{% block title_block %}
    {% if article %}
        {{ article.title }}
    {% else %}
        Unknown Article
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if article %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">{{ article.title }}</h1>
            <strong id="like_count">{{ article.views }}</strong> views
        </div>
    </div>
        <p>{{ article.content }}</p>
    {% else %}
        The specified article does not exist.
    {% endif %}

    {% if comments %}
    <ul id="commentsOver">
        {% for comment in comments %}
            <li  class="commentStyle">
                <h4>{{ comment.user }}</h4>
                <div class="commentStyleLine">
                    <p class="commentStyleContent">{{ comment.comments }}</p>
                    <p class="commentStyleTime">time: {{ comment.time }}</p>
                </div>
            </li>
        {% endfor %}
    </ul>
    {% else %}
        There are no comments exist.
    {% endif %}
    {% if user.is_authenticated %}
        <a href="{% url 'coffquiz:add_comment' article.slug %}">Add a Comment</a>
    {% endif %}
{% endblock %}

templates/coffquiz/base.html
<!DOCTYPE html>
{% load static %}
{% load coffquiz_template_tags %}
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
        Coffquiz - {% block title_block %}How to Tango with Django!{% endblock %}
    </title>
    
    <!-- Bootstrap core CSS -->
    <link href='{% static "css/bootstrap.min.css" %}' rel="stylesheet">
    
    <!-- Custom styles for this template -->
    <link href='{% static "css/dashboard.css" %}' rel="stylesheet">
    </head>
    
    <body class="background">
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
                <a class="navbar-brand p-2" href="{% url 'coffquiz:index' %}">CoffQuiz</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'coffquiz:index' %}">Home</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'coffquiz:about' %}">About</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'coffquiz:all_coffee' %}">Coffee</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'coffquiz:all_articles' %}">Articles</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'coffquiz:add_coffee' %}">Add Coffee</a></li>
                        <li class="nav-item"></li><a class="nav-link" href="{% url 'coffquiz:profile' user.username %}">My Account</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/coffquiz/">Log out</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Sign up</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Log in</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>
        
        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar background">
                    <div class="w-75 ml-3">
                        <input type="search"
                               id="search-input"
                               class="form-control ds-input"
                               placeholder="Search..." />
                    </div>

                    <div class="sidebar-sticky background" id="coffeelist-listing">
                        {% block sidebar_block %}
                            {% get_coffee_list coffee %}
                        {% endblock %}
                    </div>
                </nav>
                
                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">		
                    {% block body_block %}{% endblock %}
                    
                    <!-- FOOTER -->
                    <footer>
                        <p class="float-right"><a href="#">Back to top</a></p>
                        <p>&copy; 2021 Bingo with CoffQuiz &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
                    </footer>
                </main>
            </div>
        </div>

        <!-- Coffquiz JavaScript-->
        <script src="{% static "js/jquery-3.3.1.min.js" %}"  crossorigin="anonymous"></script>
        <script src="{% static "js/coffquiz-ajax.js" %}" crossorigin="anonymous"></script>

        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script type="text/javascript">
            window.jQuery || document.write('<script src="{% static "js/jquery-slim.min.js" %}"><\/script>')
        </script> 
        <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
        <!-- <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script> -->
        <!-- <script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" ></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script> -->
        <script src="{% static "js/bootstrap.bundle.min.js" %}" ></script>
        <script src="{% static "js/feather.min.js" %}"></script>
        <script src="{% static "js/dashboard.js" %}"></script>
    </body>
</html>

templates/coffquiz/coffee.html
{% extends 'coffquiz/base.html' %}
{% load static %}

{% block title_block %}
    {% if coffee %}
        {{ coffee.name }}
    {% else %}
        Unknown Coffee
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if coffee %}
        <div class="jumbotron p-4"> 
            <div class="container"> 
                <h1 class="jumbotron-heading">{{ coffee.name}}</h1>
                <!-- This is part is for add likes-->
                <div>
                    <strong id="like_count">{{ coffee.likes }}</strong> likes
                    {% if user.is_authenticated %}
                        <button id="like_btn"
                                data-coffeeid="{{ coffee.id }}"
                                class="btn btn-primary btn-sm"
                                type="button">
                            <span data-feather="thumbs-up"></span>
                            Like Coffee
                        </button>
                    {% endif %}
                </div>
            </div> 
        </div>
        <p>{{ coffee.description }}</p>
        {% if articles %}
            <ul>
            {% for article in articles %}
                <li>
                    <a href="{% url 'coffquiz:goto' %}?article_id={{ article.slug }}">{{ article.title }}</a>
                    {% if article.views > 1 %}
                        ({{ article.views }} views)
                    {% elif article.views == 1 %}
                        ({{ article.views }} views)
                    {% endif %}
                </li>
            {% endfor %}
            </ul>
        {% else %}
            <strong>No articles currently in this coffee.</strong><br />
        {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url 'coffquiz:add_article' coffee.slug %}">Add Article</a><br />
        <hr />
        <div>
            <form class="form-inline" id="user-form" method="post" action="{% url 'coffquiz:show_coffee' coffee.slug %}">
                {% csrf_token %}
                <div class="form-group">
                    <input class="form-control" type="text" size="50" name="query" id="query" />
                </div>
                <button class="btn btn-primary" type="submit" name="submit">Search</button>
            </form>
        </div>
        <div>
            {% if result_list %}
            <h2>Results</h2>
            <div class="list-group">
            {% for result in result_list %}
                <div class="list-group-item">
                    <h3 class="list-group-item-heading">
                        <a href="{{ result.link }}">{{ result.title|safe|escape }}</a>
                    </h3>
                    <p class="list-group-item-text">
                        {{ result.summary|safe|escape }}
                    </p>
                </div>
            {% endfor %}
            </div>
            {% endif %}
        </div>
        {% endif %}
    {% else %}
        The specified coffee does not exist.
    {% endif %}
{% endblock %}